name: Mercedes-benz.io - A Class Diesel Vehicles Test
on: 
  push: 
    branches: [ main ]
    paths: 
     - 'cypress/**'
  schedule:
    - cron: '0 16 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Add your test commands here to run the tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          browser: chrome
          version: latest

