name: Mercedes-benz.io - A Class Diesel Vehicles Test
on: 
  push: 
    branches: [ main ]
    paths: 
     - 'cypress/**'
  schedule:
    - cron: '0 16 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Add your test commands here to run the tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          browser: chrome
          version: latest
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
